---
title: "高知工科大 教員採用試験コーチング 26'永国寺"
date: today
author: "Yamato Fujii"
format:
  html:
    toc: true
    toc-title: "目次"
    number-sections: true
lang: ja
---

|氏名|教科|実績|
|--|--|--|
|Yamato Fujii|社会科|岐阜県中学校教諭（社会科）合格|

## 概要

このコーチングは、教員採用試験の主に２次試験対策を行うことを目的とする。
指導する学生は今年度の教員採用試験合格者であるが、受験自治体によって試験内容は異なるため、指導する学生がすべての試験内容に対応できるわけではないことに留意すること。

**対応可能な試験内容**

|氏名|対応できる試験内容|
|--|--|
|Yamato Fujii|模擬授業（社会科 主に中学校）</br> 面接 </br> 場面指導 </br> 小論文|

※集団討論は対応できません。集団面接は、本格的な対策はできないことをあらかじめご了承ください。

## 日程

コーチングはオリエンテーションを含め全８回実施するものとする。

<iframe src="https://calendar.google.com/calendar/embed?src=6890246510b33a8b57c413d9f0803f1a10432e2cb17ce99e50b57a85531c6693%40group.calendar.google.com&ctz=UTC" style="border: 0" width="550" height="400" frameborder="0" scrolling="no"></iframe>

## 担当学生

|模擬授業（数学科）|模擬授業（社会科）|面接|場面指導|小論文|
|--|--|--|--|--|
||Yamato Fujii|全員|Yamato Fujii|Yamato Fujii|

## 宿題

* 受験自治体およびその自治体の試験内容を調べて各担当者に報告
* 各担当者と日程調整の実施

### 面接対策をする学生へ

* 面接ノートの作成
  * 志望動機
  * なぜその自治体を志望したのか
  * なぜその校種・教科
  * ガクチカと教員としてどう生かすか（あれば）
  * 自己PR　１分or30秒くらいのもの
  * その他聞かれそうと自分で想定している質問
  
    ※いずれも１分以下の短い分量で書くこと。

    ※練習では、この質問以外にも質問する。

  
::: {.callout-note}
  
  面接の過去問は教職課程支援室のPC内に存在する。それを参考に面接ノートを作成することをお勧めする。例えば、教科に関する口頭試問的な質問をする自治体もあれば一切触れない自治体もある。自治体の傾向を掴んでおくことが重要である。
  
:::
  

### 模擬授業をする学生へ

* 指導案作成（受験自治体に提出する必要のある学生のみ）
* 模擬授業　発表準備
  * 各受験自治体の実施条件で行う
  * 単元は任意
  * 板書に関しては、**各県によって決められている方式**がある。県の授業改善資料などでやり方や形式が公開されている場合があるので、それを参考にすること。


::: {.callout-note}

こちらも過去問は教職課程支援室のPC内に存在する。まずはその単元でやってみるのが良いだろうと思う。

:::


::: {.callout-tip}
# 中学校社会科の学生へ

資料を載せておくので、参考にするとよい。

* [社会科授業づくりスライド　©岐阜県教育委員会事務局](https://webc.gifu-net.ed.jp/syakai/plan/)
* [社会科の授業の導入の仕方　©Yamato_Fujii](dounyu.qmd)

:::

教育実習の練習だと思ってやろう！

### 小論文の学生へ

* 受験自治体の過去問を題材にまずは自分なりに小論文を書いて、問題と解答を担当者へ送付
  * 小論文は、まず書かないと対策が始められない！
  * つたなくてもよいので、まずは自分なりに書いてみる
  * 書いているうちに自分の教育知識の無さにつらくなってくると思うが、あとから徐々に勉強すればよいので、とりあえず書くこと。

### 集団面接の学生へ

あんまり大した対策ができない...!申し訳ないです。

ただ先輩経験者から聞くと、総じていうのは**ほかの受験者の話を聞いているか**と**回答は短く端的に**が鉄則！

個人面接と似ているところは多々あるので、個人面接でやりましょう。


### 担当学生へ

* （担当者へ）日程調整完了次第B205 or B206 の教室確保


---

以上。